FROM --platform=linux/amd64 alpine:latest as build

COPY install-build-pkgs /tmp/
RUN /tmp/install-build-pkgs

ARG BUILD_TIMESTAMP=0
ARG GIT_REPO
ARG BRANCH
RUN git clone --single-branch --branch="${BRANCH}" ${GIT_REPO} /tmp/mergerfs 

WORKDIR /tmp/mergerfs
RUN make NDEBUG=1 LTO=1 STATIC=1 -j$(nproc) install

ENTRYPOINT ["/usr/local/bin/mergerfs","-f","/tmp","/mnt"]
